import os
DEBUG_MODE = os.path.exists(".debug")

BCRYPT_SALT_ROUNDS = 14

TOKEN_EXPIRY_TIME = 30 * 24 * 60 * 60 # 30 days in seconds

POSTS_PER_PAGE = 10

UPLOAD_FOLDER = "post_media"

MIN_TITLE_LENGTH = 3
MAX_TITLE_LENGTH = 125
MAX_BODY_LENGTH = 10000
MAX_UPLOAD_SIZE = 25

MIN_USERNAME_LENGTH = 3
MAX_USERNAME_LENGTH = 15